apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  AWS_REGION_NAME: {{ .Values.env.AWS_REGION_NAME | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.env.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.AWS_SECRET_ACCESS_KEY | b64enc }}
  AWS_S3_BUCKET: {{ .Values.env.AWS_S3_BUCKET | b64enc }}