apiVersion: v1
kind: Namespace
metadata:
  name: cloudesk
  labels:
    app: cloudesk
---

apiVersion: v1
kind: Secret
metadata:
  name: cloudesk-secret
  namespace: cloudesk
  labels:
    app: cloudesk
type: Opaque
stringData:
  owner: https://github.com/wffger/cloud-desk
data:
  AWS_REGION_NAME: "YXAtc291dGhlYXN0LTE="
  AWS_ACCESS_KEY_ID: "xxx="
  AWS_SECRET_ACCESS_KEY: "xxx="
  AWS_S3_BUCKET: "xxx="

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudesk
  name: cloudesk
  namespace: cloudesk
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cloudesk
  template:
    metadata:
      labels:
        app: cloudesk
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: cloudesk
          image: ghcr.io/wffger/cloud-desk:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 30
          envFrom:
          - secretRef:
              name: cloudesk-secret

---

apiVersion: v1
kind: Service
metadata:
  name: cloudesk-svc
  namespace: cloudesk
  labels:
    app: cloudesk
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: cloudesk