apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudesk
  namespace: argocd
spec:
  project: default
  source:
    path: helm
    repoURL: "https://github.com/wffger/cloud-desk.git"
    helm:
      parameters:
      - name: env.AWS_REGION_NAME
        value: ""
      - name: env.AWS_ACCESS_KEY_ID
        value: ""
      - name: env.AWS_SECRET_ACCESS_KEY
        value: ""
      - name: env.AWS_S3_BUCKET
        value: ""
  destination:
    namespace: cloudesk
    server: "https://kubernetes.default.svc"
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true